lib/app.js, lib/proxy.js, package.json, spec/proxy.spec.js
Rival to https://github.com/TerriaJS/terriajs-server/pull/9.
- Fixes the problem described in that PR where the entire request was being passed through including headers
- Adds unit tests for this case
- Makes the requests that come back stream directly to the client instead of waiting for the entire request to come back and then passing it all at once.
So in addition to fixing that problem this should make all our proxy requests a bit quicker and a bit more memory efficient :).
=> Exclude headers

lib/app.js, lib/feedback.js
Adds a `/feedback` service.  When properly configured with a GitHub access token in the server config file, it allows feedback issues to be created by posting a title, body, and email address.  If not configured, the service is not added.
=> Add feedback service

lib/controllers/proxy.js
This means that if a client is passing a fake `X-Forwarded-For` header then we will still append their real source ip.
=> Append to X-Forwarded-For if it already exists.

package.json
We've had this wrong all along, but I just noticed because [yarn](https://github.com/yarnpkg/yarn) seems to actually enforce it.
=> Require node >= 4.0, instead of strictly requiring 4.x.

lib/controllers/feedback.js
Adds the share url sent by TerriaJS (see terriajs#2243) to the feedback sent to github, and reorder so comments show up in email snippets before user details.
=> 2119 add shareurl to feedback

CHANGES.md, stop_server.sh
The problem was that node was being used to get the process ID, yielding a Windows process ID.  But then we were trying to use the unixy `kill` command to stop it, which expected a unixy process ID.  The change here is to use node to kill the process too.
The terriajs.pid file still isn't cleaned up properly on Windows because the SIGTERM handler is never called, but we can live with that.
=> Make `npm stop` / `stop_server.sh` work on Windows systems.

lib/controllers/proxy.js, spec/proxy.spec.js
To test add this service to a Terria instance configured to access it through the proxy:
http://location.sa.gov.au/arcgis3/rest/services/AREMI/Cereal_Straw/MapServer/
=> Fix so that we do not send a `content-length: 0` HTTP header for GET requests

CHANGES.md, lib/controllers/esri-token-auth.js, lib/makeserver.js, serverconfig.json.example
This implementation is insecure in that it effectively takes a service which is secured by username and password and allows anyone (everyone) to anonymously mint tokens for this service. This implementation only obfuscates token generation and worse it masks the fact that the layer was secured and now it is not and becomes effectively publicly available (effectively anyone could mint tokens using this service and then connect directly to the server by-passing authentication for as long token is valid). This implementation does not currently explicitly log information about the clients requesting tokens. If this is problematic in the future further steps should be taken to secure this operation such as authenticating the user prior to minting tokens and taking security more seriously such …
=> terriajs 2588 server implementation

lib/controllers/esri-token-auth.js
This implementation only warns against HTTPS being used between the terriajs-server and the esri token server. It does not warn against HTTPS in the layer URL between the client and the layer server (which would expose the token), but technically the URL here is a guide since the client could do or send the token anywhere.
=> [TerriaJS/terriaJS#2588] esri-token-auth: Add warnings to console.error for bad configurations.

lib/app.js
Fix the server so that "--public false" doesn't fork and starts in single process mode.
=> Fix single process mode.

CHANGES.md, lib/controllers/proxy.js, proxyauth.json.example, spec/proxy.spec.js
Adds support for server-supplied custom headers, by extending the process used to insert the basic http auth header `authorization`.
Improves on #66.
This is required for Protari, but may be more general purpose.
=> Support for custom auth headers

CHANGES.md, lib/controllers/proxy.js
* Fixed a problem where a proxy error (such as an invalid content length) detected after the proxy had started sending the response would cause the worker to crash with an exception saying "Can't set headers after they are sent."
* Added `Strict-Transport-Security` to the list of response headers that are not passed through to the client by the proxy.
Fixes #76 
Fixes #77
=> Proxy improvements

lib/makeserver.js, serverconfig.json.example
Add this to your server config:
```
"redirectToHttps": true,
```
You can also add a list of hosts for which requests will _not_ be redirect:
```
"httpAllowedHosts": [
"localhost"
]
```
It defaults to `localhost`, as above.
All requests (including the proxy) will be redirected except `/ping`.
Fixes TerriaJS/terriajs#3075
=> Add option to redirect to HTTPS

CHANGES.md, lib/controllers/convert.js
`fs.unlink` is currently used without a callback but node.js versions 10+ throw an exception on missing callback. Use `fs.unlinkSync` in its place.
=> Fix fs.unlink call failing

CHANGES.md, lib/controllers/share.js
This increases the accepted size of post data to the `share` endpoint. This ought to resolve issue https://github.com/terriajs/terriajs/issues/3510
=> Increase limit on post body size for share endpoint

CHANGES.md, lib/controllers/proxy.js, lib/makeserver.js, serverconfig.json.example, spec/proxy.spec.js
This PR enables you to attach additional parameters to a query string on a proxied url based on a domain name.
This is helpful if you need to append an api key that you don't want to display in the browser, and `Authorization` header is not available.
````
// serverconfig.json
{
"appendParamToQueryString": {
"somdomain.io": {
"apikey": "1234"
}
}
}
Request to 
=> https://somedomain.io/whatever
becomes
=> https://somedomain.io/whatever?apikey=1234
````
=> Assign additional params to the query string on a proxied url

CHANGES.md, lib/controllers/share.js, lib/makeserver.js, serverconfig.json.example
I was getting `PayloadTooLargeError: request entity too large` due to the create share link request payload being > 200kb (the previous hard coded default).
So I added a `shareMaxRequestSize` server option!
=> Added share max request option

lib/controllers/proxy.js
This PR fixes a bug where the server throws an error if the remote host returns a 30x response with a location header containing a relative URL with no hostname. In that case we default to the remoteUrl host.
=> Fix server crash when remote host returns a redirect url with no hostname

CHANGES.md, lib/controllers/feedback.js, package.json
https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/
=> * Authorisation token for feedback to be placed in header

spec/support/jasmine.json
There are no jasmine helpers,
so remove the config for them
to remove a:
Message:
Uncaught exception: Error: ENOENT: no such file or directory, scandir '/app/spec/helpers'
Stack:
error properties: Object({ errno: -2, code: 'ENOENT', syscall: 'scandir', path: '/app/spec/helpers' })
Error: ENOENT: no such file or directory, scandir '/app/spec/helpers'
at Object.readdirSync (node:fs:1508:26)
error from the tests.
=> jasmine.json: remove helpers section

.github/workflows/ci.yml
This replaces the old Travis CI action.
The tests do not pass with 10.x, 12.x, 14.x,
or 16.x, so put non-EOL'd versions of Node.js
in the build matrix.
=> CI: add Github action for npm test

.github/workflows/ci.yml, CHANGES.md, lib/controllers/proxy.js, spec/proxy.spec.js
- **Fix upstream proxied POST request being aborted early on Node 16+**
- **Include node 16 in tests**
- **Fix warning**
Node 16 changed when the "close" event of IncomingMessage `req` is fired. This used to be fired when the socket was closed before the request finished. Now, to better match the ReadableStream interface, it is fired when the stream representing the downstream request (from TerriaMap) closes - i.e. when the entire request has been parsed by node.js - so this event is now fired for every request and in most cases before the proxied request has finished. Since our proxy controller aborts the upstream request on this event, that means that our proxy controller is now trying to abort every upstream request. This seems to only affect POST requests, but it's possible it could …
=> Fix proxy POST

lib/controllers/share.js, serverconfig.json.example
Allows for custom S3 endpoints to be added to the server config.
This pull request includes updates to the S3 configuration in the `lib/controllers/share.js` file and the `serverconfig.json.example` file to support custom S3 endpoints. These changes enhance the flexibility of the S3 service configuration.
Configuration updates:
* [`lib/controllers/share.js`](diffhunk://#diff-25280ebd6726f4002498beb49d25bc2058d4ec6df779ffcc7a75bd26d14929cbR86): Added support for a custom S3 endpoint by updating the AWS configuration to include the `endpoint` option if provided in `serviceOptions`.
* [`serverconfig.json.example`](diffhunk://#diff-8f1a24d2bd2d8e4f22f388463d88186fbe7f6080b168f1ecf9da6914b77538d9R144-R146): Added an optional `endpoint` field to allow users to specify a custom S3 endpoint in …
=> Adding S3 Endpoint Config Option

lib/controllers/share.js, package.json, yarn.lock
Addresses CVE (although it doesn't affect our usage) - https://github.com/TerriaJS/terriajs-server/security/dependabot/57
=> Upgrade base-x to 5.x+.

CHANGES.md, lib/makeserver.js, package.json, yarn.lock
This replaces express-brute with
rate-limiter-flexible, which
removes the dependency on the vulnerable
underscore version, and does not have
a rate limit bypass vulnerability.
=> Replace express-brute

spec/ratelimit.spec.js
Accounts for difference in how node-rate-limiter and express-brute tests limit.
=> Fix specs for node-rate-limiter.

CHANGES.md, package.json
CHANGES:
* Requires Node 20.
* Replace express-brute with rate-limiter-flexible (fixes GHSA-984p-xq9m-4rjw).
* Upgraded bunch of dependencies: body-parser, express, supertest, base-x, proj4 etc.
=> Release version to 4.0.2.

lib/controllers/proxy.js, spec/proxy.spec.js
Make sure proxy strips `Cookie` and `Authorization` headers when proxying.
=> Strip Cookie and Authorization headers when proxying.
